meta_product_name: "Briiik"
meta_title: "Briiik - Gaspillage, économie, BTP, chantier"
meta_description: "Vous gérez un chantier?

Economisez de l’argent, du temps et de l’espace
sur la collecte des déchets.
Vous travaillez sur un chantier ?

Mettez en ligne les matériaux non utilisés
et augmentez vos primes
Vous faites des travaux chez vous?

Récupérez des matériaux à proximité et à moindre coût.
La consommation responsable vous parle?

RejoignezBRIIIK et construisons ensemble
l’économie circulaire du BTP , brique par brique."
meta_image: "helmet.svg" # should exist in `app/assets/images/`
